### ISSUE TITLE
값 타입 컬렉션

### ISSUE THREAD

**Issue by ji-hyeon97** [DKU-D-Coding-teams/2023-1-developers#25]
https://github.com/DKU-D-Coding-teams/2023-1-developers/blob/23d566bb3521773996c9e110aea84d1b9427c037/backend/src/main/java/backend/dankook/domain/Profile.java#L31-L32

개념적으로 값 타입 컬렉션을 사용하고 자 하는 것으로 이해했는데 오류가 나요

@dongsuu  님

작업하시다가 계속 서버 오류나면 
<img width="397" alt="스크린샷 2023-03-25 오후 11 53 06" src="https://user-images.githubusercontent.com/79920930/227724767-7d77de23-5e31-4ea4-98b6-ce1f74117fc1.png">
`@ElementCollection` 하나 작성해 두시면 될 것 같습니닷 !!

**Comment by dongsuu** [comment]
아 그러네요! Enum type list를 RDB에 적용하려면 @ElementCollection 어노테이션이 필요한게 맞는 것 같습니다! 감사합니다 :)
